
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: dev
    ports:
      - 8080:8080
    command: npm run dev

  db:
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_station
    ports:
      - 5432:5432

volumes:
  db-data: