services:
  redis:
    image: redis:7.2.2-bookworm
    restart: unless-stopped
    networks:
      - 'default'

  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_station_dev
    networks:
      - 'default'

  app:
    build: .
    restart: unless-stopped
    # ports:
    # - 8080:8080
    # - 5555:5555 # prisma studio
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=weatherapi.bladesheng.com,www.weatherapi.bladesheng.com
      - VIRTUAL_PORT=8080
    networks:
      - 'nginx_proxy_net'
      - 'default'

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - 'default'

volumes:
  db-data:

networks:
  nginx_proxy_net:
    external: true
