services:
  redis:
    image: redis:7.2.2-bookworm
    restart: unless-stopped

  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_station_dev

  app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
      # - 5555:5555 # prisma studio
    depends_on:
      - redis
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.25.3-bookworm
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env

volumes:
  db-data:
