# This workflow automatically builds and deploys the source code to fly.io
# after push or merge to main branch

name: Deploy to fly.io

on:
  # when pushing to main
  push:
    branches: [main]

  # or run this manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent run
concurrency:
  group: "fly-deploy"

jobs:
  job-1:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build --file Dockerfile.ci --tag ci-image .

      - name: Run the Docker image
        run: |
          docker run \
            --name ci-container \
            --env FLY_API_ACCESS_TOKEN=${{ secrets.FLY_API_ACCESS_TOKEN }} \
            --env FLY_APP_NAME=${{ secrets.FLY_APP_NAME }} \
            ci-image
